# Generated by Django 5.2 on 2025-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=60)),
                ('number_car', models.CharField(max_length=9)),
                ('serial_number_car', models.IntegerField()),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_name', models.CharField(max_length=90)),
                ('date_register_cargo', models.DateTimeField()),
                ('weight', models.IntegerField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryDriverlicense',
            fields=[
                ('id_category_driverlicense', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category_driverlicense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=60)),
                ('date_register', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mid_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_register', models.DateTimeField()),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driverlicense',
            fields=[
                ('number_driverlicense', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('seria_driverlicense', models.CharField(max_length=6, unique=True)),
                ('get_date', models.DateField()),
            ],
            options={
                'db_table': 'driverlicense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inn',
            fields=[
                ('number_inn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('get_date', models.DateField()),
            ],
            options={
                'db_table': 'inn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number_passport', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('serial_passport', models.CharField(max_length=4, unique=True)),
                ('get_date', models.DateField()),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'passport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PutyList',
            fields=[
                ('puty_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_sending', models.DateTimeField()),
                ('date_arrival', models.DateTimeField()),
                ('price_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('all_km', models.FloatField()),
                ('all_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=20)),
                ('date_register_putylist', models.DateTimeField()),
                ('date_update_putylist', models.DateTimeField()),
            ],
            options={
                'db_table': 'puty_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Snils',
            fields=[
                ('number_snils', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('get_date', models.DateField()),
            ],
            options={
                'db_table': 'snils',
                'managed': False,
            },
        ),
    ]
